spring.application.name=xulu
# Para mostrar em cores no console
spring.output.ansi.enabled=ALWAYS

# Hibernate ddl auto (create, create-drop, update):
# "create": derruba as tabelas e cria novas
# "create-drop": elimina o banco e recria a cada reinício (tipicamente para testes)
# "update": compara o banco com o modelo de entidades e atualiza, sem apagar valores, tabelas ou colunas antigas
spring.jpa.hibernate.ddl-auto=create

# Para mostrar as cláusulas SQL no console enquanto testamos
spring.jpa.show-sql=true

server.port = 5000

# Configurações MySql
# Substitua "nomeDoBancoDeDados" pelo nome do banco que você criar. Verifique a porta do servidor (pode ser diferente de 3306)
spring.datasource.url=jdbc:mysql://localhost:3306/xulambs?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Usuário e senha definidos no container
spring.datasource.username=mysql
spring.datasource.password=xulambs